name: massage-plans
services:
  sorokchat.database:
    image: postgres:18-alpine
    container_name: massage-plans.database
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: massage-plans
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata