spring:
  application:
    name: massage-plans-server
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/massage-plans
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081
tokens:
  access:
    lifetime: 15m
    secret-key: '{"kty":"oct","k":"COlAdHmlpjs6vNscfaEIpnMquBy2HUeVYZgrLW7h0VQwvQpN1Xe1iixfS2UqJC7r"}'
  refresh:
    lifetime: 7d
    secret-key: '{"kty":"oct","k":"1bRe3qVIqtgRHFYCf1cItv9qktUnLLXK"}'